name: Build and Release

on:
  workflow_dispatch:
    inputs:
      quickjs_version:
        description: 'QuickJS version'
        required: true
        default: '2024-01-13'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential mingw-w64

      - name: Run fetch_and_build.sh (Linux)
        run: bash fetch_and_build.sh

      - name: Rename and Collect Linux Artifacts
        run: |
          mkdir -p artifacts-linux
          find . -name '*.a' -exec bash -c 'cp {} artifacts-linux/$(basename {} "-linux-x86_64.a")' \;

      - name: Run fetch_and_build.sh (Windows)
        run: echo "y" | bash fetch_and_build.sh --window

      - name: Rename and Collect Windows Artifacts
        run: |
          mkdir -p artifacts-windows
          find . -name '*.lib' -exec bash -c 'cp {} artifacts-windows/$(basename {} "-windows-x86_64.lib")' \;

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux-artifacts
          path: ./artifacts-linux/

      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: windows-artifacts
          path: ./artifacts-windows/

  release:
    needs: build
    runs-on: ubuntu-latest
    env:
      QUICKJS_VERSION: ${{ github.event.inputs.quickjs_version }}
    steps:
      - name: Download Linux Artifacts
        uses: actions/download-artifact@v2
        with:
          name: linux-artifacts
          path: ./artifacts-linux

      - name: Download Windows Artifacts
        uses: actions/download-artifact@v2
        with:
          name: windows-artifacts
          path: ./artifacts-windows

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.quickjs_version }}.${{ github.run_number }}
          release_name: QuickJS Release ${{ github.event.inputs.quickjs_version }}
          draft: false
          prerelease: false

      - name: Upload Linux Release Assets
        run: |
          for file in artifacts-linux/*; do
            if [ -f "$file" ]; then
              curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Content-Type: application/octet-stream" \
              "https://uploads.github.com/repos/DarcJC/QuickJS-build/releases/${{ steps.create_release.outputs.id }}/assets?name=$(basename "$file")" \
              --data-binary @"$file"
            fi
          done

      - name: Upload Windows Release Assets
        run: |
          for file in artifacts-windows/*; do
            if [ -f "$file" ]; then
              curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              -H "Content-Type: application/octet-stream" \
              "https://uploads.github.com/repos/DarcJC/QuickJS-build/releases/${{ steps.create_release.outputs.id }}/assets?name=$(basename "$file")" \
              --data-binary @"$file"
            fi
          done
