name: Build and Release Multiple Platforms

on:
  workflow_dispatch:
    inputs:
      quickjs_version:
        description: 'QuickJS version'
        required: true
        default: '2024-01-13'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x86_64
            suffix: .a
            build_args: ""
          - os: ubuntu-latest
            platform: linux
            arch: i386
            suffix: .a
            build_args: "CC=gcc -m32 CXX=g++ -m32"
          - os: windows-latest
            platform: windows
            arch: x86_64
            suffix: .lib
            build_args: "CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++"
          - os: macos-latest
            platform: macos
            arch: x86_64
            suffix: .a
            build_args: ""
          - os: macos-latest
            platform: macos
            arch: arm
            suffix: .a
            build_args: ""

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential mingw-w64 gcc-multilib g++-multilib

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install make cmake gcc llvm

      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          path-type: strict
          install: >-
            curl
            base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-cmake

      - name: Run fetch_and_build.sh (Generic)
        if: runner.os != 'Windows'
        run: |
          bash fetch_and_build.sh ${{ matrix.build_args }}

      - name: Run fetch_and_build.sh (Windows)
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          bash fetch_and_build.sh ${{ matrix.build_args }}

      - name: Rename and Collect Artifacts (Generic)
        if: runner.os != 'Windows'
        run: |
          mkdir -p artifacts-${{ matrix.platform }}-${{ matrix.arch }}
          find . -name '*.lib' -exec bash -c 'cp {} artifacts-${{ matrix.platform }}-${{ matrix.arch }}/$(basename {} | sed "s/quickjs/quickjs-${{ matrix.platform }}-${{ matrix.arch }}/")'
          find . -name '*.so' -exec bash -c 'cp {} artifacts-${{ matrix.platform }}-${{ matrix.arch }}/$(basename {} | sed "s/quickjs/quickjs-${{ matrix.platform }}-${{ matrix.arch }}/")'
          find . -name '*.dylib' -exec bash -c 'cp {} artifacts-${{ matrix.platform }}-${{ matrix.arch }}/$(basename {} | sed "s/quickjs/quickjs-${{ matrix.platform }}-${{ matrix.arch }}/")'
          find . -name '*.dll' -exec bash -c 'cp {} artifacts-${{ matrix.platform }}-${{ matrix.arch }}/$(basename {} | sed "s/quickjs/quickjs-${{ matrix.platform }}-${{ matrix.arch }}/")'
          find .  name '*.a' -exec bash -c 'cp {} artifacts-${{ matrix.platform }}-${{ matrix.arch }}/$(basename {} | sed "s/quickjs/quickjs-${{ matrix.platform }}-${{ matrix.arch }}/")'
          echo "Finished"

      - name: Rename and Collect Artifacts (Windows)
        if: runner.os == 'Windows'
        shell: msys2 {0}
        run: |
          mkdir -p artifacts-${{ matrix.platform }}-${{ matrix.arch }}
          find . -name '*.lib' -exec bash -c 'cp {} artifacts-${{ matrix.platform }}-${{ matrix.arch }}/$(basename {} | sed "s/quickjs/quickjs-${{ matrix.platform }}-${{ matrix.arch }}/")'
          find . -name '*.so' -exec bash -c 'cp {} artifacts-${{ matrix.platform }}-${{ matrix.arch }}/$(basename {} | sed "s/quickjs/quickjs-${{ matrix.platform }}-${{ matrix.arch }}/")'
          find . -name '*.dylib' -exec bash -c 'cp {} artifacts-${{ matrix.platform }}-${{ matrix.arch }}/$(basename {} | sed "s/quickjs/quickjs-${{ matrix.platform }}-${{ matrix.arch }}/")'
          find . -name '*.dll' -exec bash -c 'cp {} artifacts-${{ matrix.platform }}-${{ matrix.arch }}/$(basename {} | sed "s/quickjs/quickjs-${{ matrix.platform }}-${{ matrix.arch }}/")'
          find .  name '*.a' -exec bash -c 'cp {} artifacts-${{ matrix.platform }}-${{ matrix.arch }}/$(basename {} | sed "s/quickjs/quickjs-${{ matrix.platform }}-${{ matrix.arch }}/")'
          echo "Finished"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts-${{ matrix.platform }}-${{ matrix.arch }}
          path: ./artifacts-${{ matrix.platform }}-${{ matrix.arch }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: ./artifacts

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.quickjs_version }}.${{ github.run_number }}
          release_name: QuickJS Release ${{ github.event.inputs.quickjs_version }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        run: |
          for file in $(find ./artifacts -name '*.dll' -o -name '*.so' -o -name '*.lib' -o -name '*.a'); do
            echo "Uploading ${file} to release..."
            curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/octet-stream" \
            "https://uploads.github.com/repos/DarcJC/QuickJS-build/releases/${{ steps.create_release.outputs.id }}/assets?name=$(basename "$file")" \
            --data-binary @"$file"
          done
